services:
  postgres:
    image: postgres:15-alpine
    container_name: edunex-postgres
    restart: always
    environment:
      POSTGRES_USER: edunex
      POSTGRES_PASSWORD: Pass@postgresql123
      POSTGRES_DB: db_master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
